# Generated by Django 2.2.4 on 2020-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200415_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_no',
            field=models.IntegerField(max_length=1000),
        ),
    ]
